<?php
/**
 * Created by PhpStorm.
 * User: win7
 * Date: 2017/7/4
 * Time: 11:07
 */

namespace DataStructure\LinearList;


class DoublyLinkedList extends \SplDoublyLinkedList
{
    public function add($index, $newval)
    {
        parent::add($index, $newval); // TODO: Change the autogenerated stub
    }

    public function pop()
    {
        parent::pop(); // TODO: Change the autogenerated stub
    }

    public function shift()
    {
        parent::shift(); // TODO: Change the autogenerated stub
    }

    public function push($value)
    {
        parent::push($value); // TODO: Change the autogenerated stub
    }

    public function unshift($value)
    {
        parent::unshift($value); // TODO: Change the autogenerated stub
    }

    public function top()
    {
        parent::top(); // TODO: Change the autogenerated stub
    }

    public function bottom()
    {
        parent::bottom(); // TODO: Change the autogenerated stub
    }

    public function count()
    {
        parent::count(); // TODO: Change the autogenerated stub
    }

    public function isEmpty()
    {
        parent::isEmpty(); // TODO: Change the autogenerated stub
    }

    public function setIteratorMode($mode)
    {
        parent::setIteratorMode($mode); // TODO: Change the autogenerated stub
    }

    public function getIteratorMode()
    {
        parent::getIteratorMode(); // TODO: Change the autogenerated stub
    }

    public function offsetExists($index)
    {
        parent::offsetExists($index); // TODO: Change the autogenerated stub
    }

    public function offsetGet($index)
    {
        parent::offsetGet($index); // TODO: Change the autogenerated stub
    }

    public function offsetSet($index, $newval)
    {
        parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    }

    public function offsetUnset($index)
    {
        parent::offsetUnset($index); // TODO: Change the autogenerated stub
    }

    public function rewind()
    {
        parent::rewind(); // TODO: Change the autogenerated stub
    }

    public function current()
    {
        parent::current(); // TODO: Change the autogenerated stub
    }

    public function key()
    {
        parent::key(); // TODO: Change the autogenerated stub
    }

    public function next()
    {
        parent::next(); // TODO: Change the autogenerated stub
    }

    public function prev()
    {
        parent::prev(); // TODO: Change the autogenerated stub
    }

    public function valid()
    {
        parent::valid(); // TODO: Change the autogenerated stub
    }

    public function unserialize($serialized)
    {
        parent::unserialize($serialized); // TODO: Change the autogenerated stub
    }

    public function serialize()
    {
        parent::serialize(); // TODO: Change the autogenerated stub
    }

}